replicas: 3
minimumMasterNodes: 2
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 200Gi
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
