apiVersion: v1
kind: Secret
metadata:
  name: algosaas-secrets
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
